In [1]:
import numpy as np
mat = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [2]:
mat[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [3]:
a=np.diag(mat,k=1)
a

array([ 2,  8, 14, 20])

In [4]:
mat[0,3:5]

array([4, 5])

In [5]:
mat[4:6,3:5]

array([[24, 25],
       [29, 30]])